export const colors={
    def_yellow:'#ffcb05',
    def_gray:'#aaaaaa',
    def_red:'#e4003e',
    def_green:'#35d830',
    def_black:'#3d3d3d'
}

export const icon1X={
    def_icon1:require('../assets/icons/1x/icon1.png'),
    def_icon2:require('../assets/icons/1x/icon2.png'),
    def_icon3:require('../assets/icons/1x/icon3.png'),
    def_icon4:require('../assets/icons/1x/icon4.png'),
    def_icon5:require('../assets/icons/1x/icon5.png'),
    def_icon6:require('../assets/icons/1x/icon6.png'),
    def_icon7:require('../assets/icons/1x/icon7.png'),
    def_icon8:require('../assets/icons/1x/icon8.png'),
    def_icon9:require('../assets/icons/1x/icon9.png'),
    def_icon10:require('../assets/icons/1x/icon10.png'),
    def_icon11:require('../assets/icons/1x/icon11.png'),
    def_icon12:require('../assets/icons/1x/icon12.png'),
    def_icon13:require('../assets/icons/1x/icon13.png'),
    def_icon14:require('../assets/icons/1x/icon14.png'),
    def_icon15:require('../assets/icons/1x/icon15.png'),
    def_icon16:require('../assets/icons/1x/icon16.png'),
    def_icon17:require('../assets/icons/1x/icon17.png'),
    def_icon18:require('../assets/icons/1x/icon18.png'),
    def_icon19:require('../assets/icons/1x/icon19.png'),
    def_iconDengue:require('../assets/icons/1x/iconDengue.png'),
}

export const icon2X={
    def_icon1:require('../assets/icons/2X/icon1.png'),
    def_icon2:require('../assets/icons/2X/icon2.png'),
    def_icon3:require('../assets/icons/2X/icon3.png'),
    def_icon4:require('../assets/icons/2X/icon4.png'),
    def_icon5:require('../assets/icons/2X/icon5.png'),
    def_icon6:require('../assets/icons/2X/icon6.png'),
    def_icon7:require('../assets/icons/2X/icon7.png'),
    def_icon8:require('../assets/icons/2X/icon8.png'),
    def_icon9:require('../assets/icons/2X/icon9.png'),
    def_icon10:require('../assets/icons/2X/icon10.png'),
    def_icon11:require('../assets/icons/2X/icon11.png'),
    def_icon12:require('../assets/icons/2X/icon12.png'),
    def_icon13:require('../assets/icons/2X/icon13.png'),
    def_icon14:require('../assets/icons/2X/icon14.png'),
    def_icon15:require('../assets/icons/2X/icon15.png'),
    def_icon16:require('../assets/icons/2X/icon16.png'),
    def_icon17:require('../assets/icons/2X/icon17.png'),
    def_icon18:require('../assets/icons/2X/icon18.png'),
    def_icon19:require('../assets/icons/2X/icon19.png'),
    def_iconDengue:require('../assets/icons/2X/iconDengue.png'),
}

export const icon3X={
    def_icon1:require('../assets/icons/3X/icon1.png'),
    def_icon2:require('../assets/icons/3X/icon2.png'),
    def_icon3:require('../assets/icons/3X/icon3.png'),
    def_icon4:require('../assets/icons/3X/icon4.png'),
    def_icon5:require('../assets/icons/3X/icon5.png'),
    def_icon6:require('../assets/icons/3X/icon6.png'),
    def_icon7:require('../assets/icons/3X/icon7.png'),
    def_icon8:require('../assets/icons/3X/icon8.png'),
    def_icon9:require('../assets/icons/3X/icon9.png'),
    def_icon10:require('../assets/icons/3X/icon10.png'),
    def_icon11:require('../assets/icons/3X/icon11.png'),
    def_icon12:require('../assets/icons/3X/icon12.png'),
    def_icon13:require('../assets/icons/3X/icon13.png'),
    def_icon14:require('../assets/icons/3X/icon14.png'),
    def_icon15:require('../assets/icons/3X/icon15.png'),
    def_icon16:require('../assets/icons/3X/icon16.png'),
    def_icon17:require('../assets/icons/3X/icon17.png'),
    def_icon18:require('../assets/icons/3X/icon18.png'),
    def_icon19:require('../assets/icons/3X/icon19.png'),
    def_iconDengue:require('../assets/icons/3X/iconDengue.png'),
}